### ISSUE TITLE
Let's merge these into cookstyle

### ISSUE THREAD

**Issue by thommay** [poise/rubocop-chef#2]
We've spent a fair chunk of time propagating cookstyle as the place to do cookbook linting, and it would be really good to get these rules into that repository so that we continue to have one place to discuss cookbook style guidelines.

**Comment by thommay** [comment]
And also thank you for doing this, it's much needed!

**Comment by coderanger** [comment]
The intent is that cookstyle will depend on this and include any non default config we want. The gem itself will stay separate and slightly more generic.

**Comment by coderanger** [comment]
Closing this out since it will continue as a project independently of cookstyle.

**Comment by coderanger** [comment]
(similarly some of these rules would make sense to include in `chefstyle` as we move more core resources to use a DSL-y format)

**Comment by thommay** [comment]
I'd be very hesitant to take this as a gem dependency in cookstyle as things stand. My hesitations are thus:
1. User confusion. We already see a tonne of bug reports in chef that are actually ohai or chef-server, simply because most users don't know how to figure out where the correct place to report something is. I foresee the same thing happening in cookstyle, which means that @tas50 and @lamont-granquist will end up shouldering most of the burden of triage.
2. Maintenance. For something this fundamental to our workflow I would like to avoid the problems of foodcritic (and - to a lesser extent - fauxhai, chefspec, etc), and ensure that a maintenance _team_ exists and (ideally) this project falls under the chef maintenance policy.
